# Travis CI будет использовать язык java.
language: java

# Версия JDK для сборки проекта
jdk: oraclejdk11

# Режим обычного пользователя для сборки проекта.
sudo: false

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# И отправлять на сервис https://codecov.io/
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="2d6f1e1f-8661-4209-82cd-e24374f97af4"
